### ISSUE TITLE
Add possibility to Import Links

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-pasteur#15]
# User Story

The importer currently lets users import spots from a simple and commonly used csv file into Mastodon. This way, users can use Mastodon’s visualization and analysis tools.

The figure shows where to find the CSV importer
![grafik](https://github.com/user-attachments/assets/dc9f0313-b39b-4743-9097-60bfe7cf4ce3)

Currently, users can select a .csv file from the file system. The importer displays the first line (aka header) of the file and lets users choose the correct order for the columns (like x, y, z, frame, label) without having to modify the csv file.

However, the “CSV Importer” can only import spots. It can’t handle links or cell divisions, which makes it very difficult to import anything that has been tracked outside of Mastodon. It may be be beneficial, if the functionality of importing links would be implemented into the CSV importer.

The figure shows the CSV importer in action and the result (unlinked spots)

![grafik](https://github.com/user-attachments/assets/abbff029-eee3-4f94-b9a9-f53fb8fefdec)

# Tasks:

- [x] Decide
  - [ ] ~Whether the initial import dialog as extended with a second file (for the links) ~
  - [ ] ~Whether there will be a separate import dialog that is just for links~
  - [x] Whether the links can be contained in a "parent" column
- [x] Add a new dialog section, where a selection of link source (i.e. parent) can be specified, similar to the existing column choices for spots

**Comment by tinevez** [comment]
A CSV file is not suitable for links. I would recommend relying on the GraphML format instead.

**Comment by stefanhahmann** [comment]
> A CSV file is not suitable for links. I would recommend relying on the GraphML format instead.

But this is how I imported these data sets into Mastodon: https://github.com/mastodon-sc/mastodon-example-data/tree/master/astec
- 1 CSV file with Spots
- 1 CSV file for links
(cf. https://github.com/mastodon-sc/mastodon-deep-lineage/blob/master/src/test/java/org/mastodon/mamut/astec/AstecReader.java)

GraphML is also a good idea, but it is more difficult to communicate, which attributes, we expect to be set in the GraphML file.

**Comment by tinevez** [comment]
Ok this is convincing. A good test would be to see whether we can reimport fully the CSV files generated with the CSV export of the table views.

**Comment by stefanhahmann** [comment]
> Ok this is convincing. A good test would be to see whether we can reimport fully the CSV files generated with the CSV export of the table views.

Exactly. [Johannes](https://github.com/jgirstmair), who was asking for this feature, and I had the same idea.

**Comment by tinevez** [comment]
Would you have a smallish couple of CSV files I could play with?

**Comment by stefanhahmann** [comment]
Yes. This Zip-File contains a `spot.csv` and a matching `links.csv`

[Pm01.zip](https://github.com/user-attachments/files/16428139/Pm01.zip)

If imported correctly, the result should be close to https://github.com/mastodon-sc/mastodon-example-data/blob/master/astec/Pm01.mastodon

I did the import using https://github.com/mastodon-sc/mastodon-deep-lineage/blob/master/src/test/java/org/mastodon/mamut/astec/AstecReader.java

**Comment by stefanhahmann** [comment]
Here is a 2nd example: 
[Pm02.zip](https://github.com/user-attachments/files/16428177/Pm02.zip)

After import, it should be similar to https://github.com/mastodon-sc/mastodon-example-data/blob/master/astec/Pm02.mastodon

**Comment by stefanhahmann** [comment]
However, these file have not been created with the Mastodon CSV export.

**Comment by stefanhahmann** [comment]
Resolved via #16
